server:
  port: 8200
management:
  server:
    port: 9200

spring:
  datasource:
    name: datasource
    druid:
      url: jdbc:mysql://127.0.0.1:3306/springboot
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: false
  profiles:
    active: dev

#mybatis配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.huixiaoer.springboot.pojo
  check-config-location: false

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql